支持指定端口号

diff --git a/bin/cls_rebuild_slave b/bin/cls_rebuild_slave
--- a/bin/cls_rebuild_slave
+++ b/bin/cls_rebuild_slave
@@ -62,9 +62,9 @@ fi
 
 PG_BASEBACKUP=$(dirname "$pgsql_pgctl")/pg_basebackup
 
-su - postgres -c "PGPASSWORD=$pgsql_reppassord $PG_BASEBACKUP -h $writer_vip -U $pgsql_repuser -D $pgsql_pgdata -X stream -P"
+su - postgres -c "PGPASSWORD=$pgsql_reppassord $PG_BASEBACKUP -h $writer_vip -p $pgsql_pgport -U $pgsql_repuser -D $pgsql_pgdata -X stream -P"
 if [ $? -ne 0 ]; then
-	echo "failed to call \"$PG_BASEBACKUP -h $writer_vip -U $pgsql_repuser -D $pgsql_pgdata -X stream -P\"" >&2
+	echo "failed to call \"$PG_BASEBACKUP -h $writer_vip -p $pgsql_pgport -U $pgsql_repuser -D $pgsql_pgdata -X stream -P\"" >&2
 	./cls_unstandby_node $nodename >/dev/null 2>/dev/null
 	exit 1
 fi
diff --git a/bin/cls_repair_by_pg_rewind b/bin/cls_repair_by_pg_rewind
--- a/bin/cls_repair_by_pg_rewind
+++ b/bin/cls_repair_by_pg_rewind
@@ -52,9 +52,9 @@ fi
 
 PG_REWIND=$(dirname "$pgsql_pgctl")/pg_rewind
 
-su - postgres -c "$PG_REWIND -D $pgsql_pgdata --source-server='host=$writer_vip dbname=template1 user=$pgsql_repuser password=$pgsql_reppassord' -P"
+su - postgres -c "$PG_REWIND -D $pgsql_pgdata --source-server='host=$writer_vip port=$pgsql_pgport dbname=template1 user=$pgsql_repuser password=$pgsql_reppassord' -P"
 if [ $? -ne 0 ]; then
-	echo "failed to call \"$PG_REWIND -D $pgsql_pgdata --source-server='host=$writer_vip' -P\"" >&2
+	echo "failed to call \"$PG_REWIND -D $pgsql_pgdata --source-server='host=$writer_vip' port=$pgsql_pgport -P\"" >&2
 	./cls_unstandby_node $nodename >/dev/null 2>/dev/null
 	exit 1
 fi
